version: "3.8"

services:
  arquivo-frontend:
    build:
      context: ./arquivo-morto-react
      dockerfile: Dockerfile
      args:
        - VITE_BASE_URL=${VITE_BASE_URL}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    restart: always

  arquivo-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADM_PASSWORD=${ADM_PASSWORD}

  postgres:
    image: postgres:latest
    container_name: postgres_arquivo_morto
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # Mapeia a porta 5432 da máquina host para a porta 5432 do contêiner
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
