version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_arquivo_morto
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always  
    volumes:
      - /volume/containers/arquivo-morto/db:/var/lib/postgresql/data

  arquivo-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADM_PASSWORD=${ADM_PASSWORD}
    volumes:
      - /volume/containers/arquivo-morto/fichas:/app/uploads
    depends_on:
      - postgres

  arquivo-frontend:
    build:
      context: ./arquivo-morto-react
      dockerfile: Dockerfile
      args:
        - VITE_BASE_URL=${VITE_BASE_URL}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    restart: always
    depends_on:
      - arquivo-backend
